### ISSUE TITLE
Have error

### ISSUE THREAD

**Issue by nicejava** [radoslawik/VRPTW_GA_PSO#1]
process_data.py", line 70, in <listcomp>
    parsed_data[DISTANCE_MATRIX] = [[calculate_distance(parsed_data[c1], parsed_data[c2]) for c1 in customers] for c2 in customers]
KeyError: 'C_{x}'

**Comment by radoslawik** [comment]
You probably executed the wrong script. In order to start the algorithm you need to execute the `run.py` with two arguments: problem name and algorithm name. For example, `python run.py R101 GA` will run the genetic algorithm with the R101.txt data.

**Comment by nicejava** [comment]
[image: image.png]

ํYes i executed run.py and set input like this above but have error "
parsed_data[DISTANCE_MATRIX]
= [[calculate_distance(parsed_data[c1], parsed_data[c2]) for c1 in
customers] for c2 in customers]
KeyError: 'C_{x}' " in  process_data.py", line 70  this below

[image: image.png]
[image: image.png]

**Comment by nicejava** [comment]
Yes i executed run.py and set input like this above but have error " parsed_data[DISTANCE_MATRIX] = [[calculate_distance(parsed_data[c1], parsed_data[c2]) for c1 in customers] for c2 in customers]
KeyError: 'C_{x}' " in  process_data.py", line 70  this below

![image](https://user-images.githubusercontent.com/6760497/116783073-f53b3500-aab6-11eb-8e6f-d40ca36c38cd.png)

![image](https://user-images.githubusercontent.com/6760497/116783097-06844180-aab7-11eb-9459-1a7bff3eb3aa.png)

![image](https://user-images.githubusercontent.com/6760497/116783103-0e43e600-aab7-11eb-9e0d-8f0578879c50.png)

**Comment by radoslawik** [comment]
Well, you have modified the code it seems, you are missing the `F` letter before `C_{x}`. You want the number to appear in the place of `x`. It should like that:
```
customers = [DEPART] + [F'C_{x}' for x in range(1, cust_num+1)]
```

**Comment by nicejava** [comment]
That worked .. thank you very musch
